Repository area4lib/area4, pull requests merged in 2018-11, with the labels that each got.

#51 Just testing some things
  .cirrus.yml
  .travis.yml
Labels: enhancement, needs-more-info

#52 Solano CI
  solano.yml
Labels: needs-more-info, todo :spiral_notepad:

#57 Cleanup
  .cirrus.yml
  .travis.yml
  CONTRIBUTING.md
  README.md
  setup.py
Labels: enhancement

#58 Doc examples
  docs/index.rst
Labels: enhancement, needs: docs

#59 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#60 Latest commits
  .cirrus.yml
  .travis.yml
  CONTRIBUTING.md
  README.md
  docs/index.rst
  setup.py
Labels: needs-more-info

#62 Prevent VSCode Telemetry
  .vscode/settings.json
Labels: enhancement, security

#63 fixing things
  .github/ISSUE_TEMPLATE/main_template.md
Labels: enhancement

#64 Clear up package info function
  area4/__init__.py
Labels: enhancement, needs-more-info

#65 Update .gitignore
  .gitignore
Labels: enhancement
