Repository area4lib/area4, pull requests merged in 2018-10, with the labels that each got.

#31 Code cleanup
  area4/__init__.py
Labels: enhancement

#39 alphabet dividiers
  area4/__init__.py
Labels: HACKTOBERFEST

#44 Added 100+ emoji dividers
  area4/__init__.py
  docs/index.rst
Labels: HACKTOBERFEST, enhancement

#46 Create stale.yml
  .github/config.yml
  .github/stale.yml
Labels: enhancement, todo :spiral_notepad:

#47 Update .cirrus.yml
  .cirrus.yml
Labels: enhancement
