Repository area4lib/area4, pull requests merged in 2019-02, with the labels that each got.

#111 run actual tests
  .cirrus.yml
  .github/config.yml
  .github/stale.yml
  .travis.yml
  MANIFEST.in
  area4/__init__.py
  requirements/dev-requirements.txt
  requirements/test.txt
  setup.py
  test-code.py
  tests/start.py
  tests/testmodule.py
Labels: bug, enhancement

#117 Begin to move onto Cirrus CI
  .cirrus.yml
  .markdownlint.yml
  .travis.yml
  CONTRIBUTING.md
  README.md
  requirements/test.txt
  test-code.py
Labels: Rewrite, enhancement, needs: docs, subject: maintaining-project, todo :spiral_notepad:

#122 Fix installing of requirements
  .cirrus.yml
Labels: CodeOwner reviewed, enhancement

#133 Move tests onto make
  .cirrus.yml
  Makefile
Labels: blocked, enhancement

#142 fixed issue
  test-code.py
Labels: enhancement, style

#150 Update changelog
  changelog.txt
Labels: subject: maintaining-project

#120 Added splitter function
  area4/__init__.py
  code_tests.py
  docs/index.rst
  docs/other.rst
Labels: enhancement

#161 Material function
  area4/__init__.py
  area4/util.py
  code_tests.py
  extras/whatthefork.txt
Labels: Enhancement
